// <auto-generated />
namespace WaidWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddUploadId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUploadId));
        
        string IMigrationMetadata.Id
        {
            get { return "201211060422231_AddUploadId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
